status:
  wait: "Joined"
  true: "Started"
  false: "Finished"
email_subject:
  last_day_month: "Report trainee in course last day of month"
  two_days_finish_course: "Notify course will finish in two days"
activities:
  subject_update: "user_subject.update_task"
  subject_finish: "user_subject.finish"
  course_assign: "user_course.create"
  course_start: "course.update"
  course_finish: "course.finish"
  assign_to_course: "Trainee assigned to a course"
